Mobile Nav Bar
MichelangeloCN/twitterClone pull request #44
Opened 2021-02-24 16:56 UTC by lisarawlings

2021-02-24 17:00 UTC, jadavey91 approved these changes

2021-02-24 17:02 UTC, Riley142 approved these changes

2021-02-24 20:01 UTC, boothscript requested changes
There are a couple of things that need to be changed on this before it can be merged.

2021-02-24 20:01 UTC, boothscript commented on app/src/App.js
>  import Header from "./Components/Header";
Header has been imported twice so will fail ESLint check

2021-02-24 20:01 UTC, boothscript commented on app/src/App.js
> +      <MobileNavBar />
You'll need to remove `<Messages />`, `<i className="ri-notification-3-line" /> `and ` <ExampleComponent />` for now.

2021-02-24 20:01 UTC, boothscript commented on app/src/Components/Messages.js
> +      <Collapsible id="Messages" trigger="Messages" i className="ri-mail-line">
it looks like you deleted an icon but left some of the code in the Collapsible tag

2021-02-25 10:03 UTC, boothscript approved these changes

2021-02-25 10:05 UTC, merged